### ISSUE TITLE
install jdk1.8.0_172, dir install dir is jdk1.8.0_172-amd64

### ISSUE THREAD

**Issue by cifaz** [srsp/ansible-oracle-java#10]
new jdk1.8.0_172, the install dir is /usr/java/jdk1.8.0_172-amd64

the errors:
```
TASK [srsp.oracle-java : link "/usr/java/default"] *************************************************************************************************************************
Wednesday 25 April 2018  15:53:57 +0800 (0:00:00.309)       0:02:29.328 ******* 
fatal: [localhost]: FAILED! => {"changed": false, "gid": 0, "group": "root", "mode": "0777", "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /usr/java/jdk1.8.0_172", "owner": "root", "path": "/usr/java/default", "secontext": "unconfined_u:object_r:usr_t:s0", "size": 16, "src": "/usr/java/jdk1.8.0_172", "state": "link", "uid": 0}
```

**Comment by srsp** [comment]
It seems to work on Debian. Which OS are you using?

**Comment by cifaz** [comment]
centos7.4

**Comment by srsp** [comment]
What version of the role are you using?

**Comment by cifaz** [comment]
ansbile: 2.5.1
srsp.oracle-java: 2.18.2  the newest version

**Comment by cifaz** [comment]
I install jdk1.8.0_172 with yum again, the default install dir is /usr/java/jdk1.8.0_172-amd64/
Maybe you should adjust the installation directory, or fixed it

**Comment by srsp** [comment]
I will take a look at it and fix it, but probably not before tonight.

**Comment by cifaz** [comment]
Thanks!
I fix it in my way, Wait for your solution.

**Comment by StanSvec** [comment]
I can confirm the same problem when trying on Amazon Linux.

**Comment by srsp** [comment]
Tarball and rpm now behave differently. Version 2.18.3 takes that into account.
