### ISSUE TITLE
Files in Role Directory

### ISSUE THREAD

**Issue by Tux12Fun** [srsp/ansible-oracle-java#12]
Hi,
thank you for your great work an the fork. I'll switched to your fork and try to support this.

Currently I have a little problem. The Role uses the Playbookdir/files for the Java Files.
In my case i place it into the role dir/files, because I download it only once an use it for many systems.

Would it be possible to change this in the install.yml?

`
    - name: copy RPM from local
      copy:
        src: "files/{{ jdk_tarball_file }}.rpm"
        dest: "{{ java_download_path }}/{{ jdk_tarball_file }}.rpm"
      when: use_rpm

    - name: copy tarball from local
      copy:
        src: "files/{{ jdk_tarball_file }}.tar.gz"
        dest: "{{ java_download_path }}/{{ jdk_tarball_file }}.tar.gz"
      when: use_tarball

    - name: copy .dmg from local
      copy:
        src: "files/{{ jdk_tarball_file }}.dmg"
        dest: "{{ java_download_path }}/{{ jdk_tarball_file }}.dmg"
      when: use_dmg
`

In my opinion, this should work for every user. If the file exists in role file/ then the file is pulled from there. If there is any file in playbook dir it will be used.

**Comment by srsp** [comment]
Thank you! I will look into this (and the other two issues) after I return from my vacation (July, 16th). All issues seem legit.

**Comment by srsp** [comment]
Hi @Tux12Fun, would you like to reuse the file, which is then in a different location than `{{ playbook_dir }}/files` or would you like to provide an alternative download url, which maybe points to a server in your local network?

**Comment by Tux12Fun** [comment]
Hi, I have the JDK Files in my Role Directory only one time und include the role in different Systems. 

So I have to strore the JDK File only once and I can deploy it to your Systems. The Systems itself doesn't have a possiblity to connect to the internet.

**Comment by Tux12Fun** [comment]
My Files are stored to role directory/files.

So if you remove {{ playbook_dir }} everything is fine.

**Comment by srsp** [comment]
Can you check if `master` fixes this issue for you?
