### ISSUE TITLE
Latest release doesn't include merged in changes.

### ISSUE THREAD

**Issue by davidjoyce-okta** [srsp/ansible-oracle-java#21]
Hey, looks like what you merged in from me wasn't included in the latest release. Could you create a release with those commits? Thank you. @srsp

**Comment by srsp** [comment]
I have to test it more thoroughly before the release. Sorry for the delay.

**Comment by srsp** [comment]
I will release by the end of this week. I did a bit of refactoring. I wanted to make configuration a bit easier, so I merged the different mirror and download options in `java_download_from`, which can take the values `oracle`, `mirror` and `local` and the single option to set the `java_mirror`, which should only be set, when `java_download_from` is set to `mirror`.

I hope I did not break any of your use cases with it.
