### ISSUE TITLE
Error for download JDK, oracle close link

### ISSUE THREAD

**Issue by shmykyta** [srsp/ansible-oracle-java#25]
Hello,
many thanks for such useful playbook, but have a problems
Of course workaround is to download by yourself and put it to `files`, but could you return functional of downloading jdk from website? ty
```
TASK [ansible-oracle-java : Download JDK (as rpm file)] ****************************************************************************************************************************************************
Thursday 25 April 2019  12:53:58 +0300 (0:00:00.851)       0:00:26.677 ******** 
fatal: [MY_HOST]: FAILED! => changed=false 
  dest: /tmp/jdk-8u201-linux-x64.rpm
  msg: Request failed
  response: 'HTTP Error 404: Not Found'
  state: absent
  status_code: 404
  url: http://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.rpm
```

**Comment by srsp** [comment]
Thanks for reporting. I will look into it.

**Comment by srsp** [comment]
So it looks like JDK 8 is only available for download after login. Up until now this has only been the case for older versions. Now it seems even the latest version (of JDK 8) is behind a login. 

I guess that means the end of support for JDK 8 for this role. JDK 12 still works, 11 I have not tried yet.

**Comment by srsp** [comment]
So to be clear: One can still download the JDK, put it in `files` and let the role do its job, but the automatic download for JDK 8 will no longer work. 
For JDK 11 the latest version is not downloadable, but the one before.
For JDK 12 the latest version is downloadable.

**Comment by shmykyta** [comment]
Agree, later will add PR with possibility download it from GCP or AWS cloud as workaround 
i guess it will be useful

**Comment by srsp** [comment]
I think you can already do that. Just define the URL in the playbook, where you uploaded the JDK, like this:

```
- java_download_from: mirror
- java_mirror: "http://some.url/jdk-8u172-macosx-x64.dmg"
```

Or what exactly do you have in mind?
