### ISSUE TITLE
JDK 13.0.1 Installation:  Error - the package path specified was invalid

### ISSUE THREAD

**Issue by braindonor** [srsp/ansible-oracle-java#30]
Hi,

Thanks for releasing this very useful project.   I'm attempting to install Oracle 13 using the following configuration:

- include_role:
        name: srsp.oracle-java
      vars:
        - java_version: 13
        - java_latest_subversion:
            13: 0.1
        - jdk_file_name: jdk-13.0.1_osx-x64_bin
        - jdk_version_detail: 13.0.1+9
        - jdk_tarball_hash: cec27d702aa74d5a8630c65ae61e4305

The download is successful, but the package installation fails due to the naming of the package (error message at the end of this post below).

I've fixed it locally by changing line 18 of use-dmg.yml by replacing " Update " with "." 

  command: installer -pkg "{{ mountpoint }}/JDK {{ java_version }}.{{ java_subversion }}.pkg" -target /

The package name is "JDK 13.0.1.pkg"

It appears that 13.0.1 is the only version that Oracle allow you to download without a login.    I'm not sure what the best fix for this issue, as it would be good to keep compatibility with old versions (which would need to be placed in the files folder or some mirror).  It would be nice if we could configure the package name using a role variable.

Regards,

Pentti

Failure Message
============

fatal: [127.0.0.1]: FAILED! => {
    "changed": true, 
    "cmd": [
        "installer", 
        "-pkg", 
        "/Volumes/JDK_13.0.1/JDK 13 Update 0.1.pkg", 
        "-target", 
        "/"
    ], 
    "delta": "0:00:00.118454", 
    "end": "2019-11-01 21:17:09.388071", 
    "invocation": {
        "module_args": {
            "_raw_params": "installer -pkg \"/Volumes/JDK_13.0.1/JDK 13 Update 0.1.pkg\" -target /", 
            "_uses_shell": false, 
            "argv": null, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "stdin_add_newline": true, 
            "strip_empty_ends": true, 
            "warn": true
        }
    }, 
    "msg": "non-zero return code", 
    "rc": 1, 
    "start": "2019-11-01 21:17:09.269617", 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "installer: Error - the package path specified was invalid: '/Volumes/JDK_13.0.1/JDK 13 Update 0.1.pkg'.", 
    "stdout_lines": [
        "installer: Error - the package path specified was invalid: '/Volumes/JDK_13.0.1/JDK 13 Update 0.1.pkg'."
    ]
}

**Comment by srsp** [comment]
Hi @braindonor, thanks for your detailed error report. Unfortunately Oracle sometimes changes some tiny details, which break automated scripts. 

I just pushed some vars for JDK 13 to master, so you can remove them in your config. I also tried to cope with the pkg name issue in a suitable manner. You can try again with the version from master.

**Comment by srsp** [comment]
Should be fixed with 3.2.0.

**Comment by braindonor** [comment]
Thanks, JDK 13 installs successfully now.
