### ISSUE TITLE
Unable to install Java 10 on Amazon Linux

### ISSUE THREAD

**Issue by StanSvec** [srsp/ansible-oracle-java#9]
I'm running the role with default values as described in the documentation however the role fails with the following error:
``amazon-ebs: fatal: [default]: FAILED! => {"changed": false, "dest": "/tmp/jdk-10.0.1_linux-x64_bin.rpm", "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "http://download.oracle.com/otn-pub/java/jdk/10.172+10/fb4372174a714e6b8c52526dc134031e/jdk-10.0.1_linux-x64_bin.rpm"}
``

**Comment by srsp** [comment]
This is fixed on master, but I did not have time to release it yet. Hopefully tonight. Great to hear that somebody uses this role to install JDK 10!

**Comment by StanSvec** [comment]
To be honest I started to have feeling that I must be doing something wrong as every ansible role for installing Java on Amazon Linux I tried failed on different error! If you are able to get this fixed I'll be extremely grateful!

**Comment by srsp** [comment]
Please try to set the `java_subversion` to `0.1` and make sure you use version 2.18.2 of the role: 

```
  vars:
    - java_version: 10
    - java_subversion: 0.1
```

There might be a bug in setting the default subversion for version 10.

**Comment by StanSvec** [comment]
Installed! Thanks a lot!

**Comment by srsp** [comment]
I will fix the bug, and update the README nevertheless.
